mexexpress/api/urls.py
from django.urls import path
from api.views import get_all_products



urlpatterns = [
    path('all_products/',get_all_products,name='all_products')
]

mexexpress/mexexpress/urls.py
from django.contrib import admin
from django.urls import path,include
from shopApp.views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('shopapp/',include('shopApp.urls')),
    path('',index),
    path('api/',include('api.urls')),
    path('accounts/',include('django.contrib.auth.urls'))
]

mexexpress/shopApp/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('',views.index,name='index'),
    path('about/',views.about,name='about'),
    path('form_comment/',views.form_comment,name='form_comment'),
    path('form_contact/',views.form_contact,name='form_contact')
]

mexexpress/api/models.py
from django.db import models

# Create your models here.

mexexpress/shopApp/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
    product_name = models.CharField(max_length=100,unique=True)
    product_description = models.CharField(max_length=255)
    product_full_cost = models.DecimalField(max_digits=8,decimal_places=2)
    product_is_offer = models.BooleanField()
    product_offer_cost = models.DecimalField(max_digits=8,decimal_places=2)

    def __str__(self):
        return self.product_name

class HistoricalCost(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    chance_date = models.DateTimeField()
    product_cost = models.DecimalField(max_digits=8,decimal_places=2)
    product_is_offer = models.BooleanField()

    def __str__(self):
        return self.product.product_name + " " + self.chance_date.strftime('%Y-%m-%d %H:%M')


class Contacts(models.Model):
    contact_full_name = models.CharField(max_length=255)
    contact_address = models.CharField(max_length=255)
    contact_phone = models.CharField(max_length=15)
    contact_email = models.EmailField(max_length=150,default='alex@gmail.com')
    contact_activate = models.BooleanField()

    def __str__(self):
        return self.contact_full_name

mexexpress/shopApp/forms.py
from django import forms
from django.core import validators


def check_for_z(value):
    if value[0].lower() != 'z':
        raise forms.ValidationError('no empieza con z')
class FormComment(forms.Form):
    full_name = forms.CharField(label='Nombre',validators=[validators.MaxLengthValidator(20),check_for_z])
    email = forms.EmailField(label='Email')
    comment = forms.CharField(label='Comentario',widget=forms.Textarea,validators=[validators.MaxLengthValidator(150)])

class FormContact(forms.Form):
    full_name = forms.CharField(label="Nombre ",max_length=255,required=True)
    address = forms.CharField(label="direccion ",max_length=255,required=True)
    phone = forms.CharField(label="Telefono ",max_length=15,required=True)
    email = forms.EmailField(label="Email ",max_length=155,required=True)
    activate = forms.BooleanField(required=True)

mexexpress/api/views.py
from django.shortcuts import render
from shopApp.models import Product
from django.http import JsonResponse
from django.core import serializers

# Create your views here.
def get_all_products(request):
    queryset = Product.objects.all()
    res = serializers.serialize("json",queryset)
    return JsonResponse(res,safe=False)

mexexpress/shopApp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse 
from .models import Product,Contacts
from .forms import FormComment,FormContact
from django.urls import reverse
# Create your views here.
def index(request):
    product_list = Product.objects.all()
    speacial_offers = Product.objects.filter(product_is_offer=True)
    productos = [
        { 
         'name' : 'Relog Citizen',
         'cost' : 150.00,
         'image': 'https://ss376.liverpool.com.mx/xl/1136440248.jpg'
         },
         {
             'name' : 'Peluche de Batman',
             'cost' : 35.00,
             'image': 'https://m.media-amazon.com/images/I/81eU3-uPjWL.jpg'
         },
         {
             'name' : 'Consola de videojuegos Xbox',
             'cost' : 500.00,
             'image': 'https://http2.mlstatic.com/D_Q_NP_942133-MLA74651936102_022024-O.webp'
         },
         {
             'name' : 'RTX 3060',
             'cost' : 350.00,
             'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuwkXO4SLaQaDrbkzzTLErafkmjAPk8fJpIw&s'
         }
    ]
    context = {
       "speacial_offers": speacial_offers,
       "product_list":product_list
       
       
    }
    return render(request,'shopApp/index.html',context)

def about(request):
    contacts_list = Contacts.objects.filter(contact_activate=True).order_by("contact_full_name")
    context = {
        'contacts': contacts_list
    }
    return render(request,'shopApp/about.html',context)

def form_comment(request):
    form = FormComment()

    if request.method == 'POST':
        form = FormComment(request.POST)
        if form.is_valid():
            print('FORMULARIO VALIDO')
            print('Nombre: ', form.cleaned_data['full_name'])
    context = {
        'form':form
    }
    return render(request,'shopApp/form_comment.html',context)

def form_contact(request):
    frmContact = FormContact()

    if request.method == 'POST':
        frmContact = FormContact(request.POST)
        if frmContact.is_valid():
            dataContact = frmContact.cleaned_data
            newContact = Contacts()
            newContact.contact_full_name = dataContact['full_name']
            newContact.contact_address = dataContact['address']
            newContact.contact_phone = dataContact['phone']
            newContact.contact_email = dataContact['email']
            newContact.contact_activate = dataContact['activate']
            newContact.save()
            return redirect('/shopapp/about/')
        
    context = {
        'frmContact':frmContact
    }

    return render(request,'shopApp/form_contact.html',context)

mexexpress/templates/shopApp/about.html
{% extends 'shopApp/base.html' %}
{% block content %}
<center><h1>Lista de contactos</h1></center>
<table class="table table-bordered border-primary">
    <thead>
        <tr>
          <th scope="col">Nombre</th>
          <th scope="col">Direccion</th>
          <th scope="col">Telefono</th>
          <th scope="col">Email</th>
        </tr>
      </thead>
      <tbody>
        
        {% for contact in contacts %}
        <tr>
          <td>{{contact.contact_full_name}}</td>
          <td>{{contact.contact_address}}</td>
          <td>{{contact.contact_phone}}</td>
          <td>{{contact.contact_email}}</td>
        </tr>
        {% endfor %}
       </tbody>
  </table>
{% endblock %}

mexexpress/templates/shopApp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Página de Inicio - MexExpress</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'shopApp/css/styles.css' %}">
</head>
<body class="bg-light">
    
    <!-- Barra de navegación -->
    <nav class="navbar navbar-expand-lg navbar-dark text-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">MexExpress</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <form class="d-flex ms-auto">
                    <input class="form-control me-2" type="search" placeholder="Buscar productos...">
                    <button class="btn btn-outline-light text-light" type="submit">Buscar</button>
                </form>
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                   
                        {% if user.is_authenticated %}
                            <a onclick="document.getElementById('logout_form').submit();" class="btn btn-link ms-3 text-light">Hola {{user}}</a>
                        {% else %}
                            <a href="{% url 'login' %}" class="btn btn-link ms-3 text-light">Iniciar Sesion</a>
                        {% endif %}
                 
                    <button class="btn btn-link ms-3 text-light" >
                        <a href="{%url 'app:about'%}" class="btn btn-link ms-3 text-light" >About</a>
                    </button>
                    <button class="btn btn-link ms-3 text-light">Carrito</button>
                </ul>
                <form id="logout_form" style="display: none;" action="{% url 'logout' %}" method="POST">
                    {% csrf_token %}
                </form>
            </div>
        </div>
    </nav>
    
   
    <div>
        {% block content %}
        {% endblock %}
    </div>
    
    <!-- Footer -->
    <footer class=" text-light text-center py-3">
        <p>Síguenos en nuestras redes sociales</p>
        <a href="#" class="text-light mx-2"><i class="fab fa-facebook"></i></a>
        <a href="#" class="text-light mx-2"><i class="fab fa-twitter"></i></a>
        <a href="#" class="text-light mx-2"><i class="fab fa-instagram"></i></a>
    </footer>
    
</body>
</html>

mexexpress/templates/shopApp/form_comment.html
{% extends 'shopApp/base.html' %}
{% block content %}

<h2>Contacto</h2>

<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn btn-primary">Enviar</button>
</form>

{% endblock %}

mexexpress/templates/shopApp/form_contact.html
{% extends 'shopApp/base.html' %}
{% block content %}

<h2>Contacto</h2>

<form method="POST">
    {% csrf_token %}
    {{frmContact.as_p}}
    <button type="submit" class="btn btn-primary">Enviar</button>
</form>

{% endblock %}

mexexpress/templates/shopApp/index.html
{% extends 'shopApp/base.html' %}
{% block content %}
    
    <!-- Carrusel -->
    <div id="carouselExample" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="https://placehold.co/1200x400" class="d-block w-100" alt="Noticia 1">
            </div>
            <div class="carousel-item">
                <img src="https://placehold.co/1200x400" class="d-block w-100" alt="Noticia 2">
            </div>
            <div class="carousel-item">
                <img src="https://placehold.co/1200x400" class="d-block w-100" alt="Noticia 3">
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
            <span class="carousel-control-prev-icon"></span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
            <span class="carousel-control-next-icon"></span>
        </button>
    </div>
    
    <!-- Tabla de ofertas -->
    <div class="container my-4">
        <h2 class="text-center">Ofertas Especiales</h2>
        <table class="table table-striped table-bordered">
            <thead class="">
                <tr>
                    <th>Imagen</th>
                    <th>Producto</th>
                    <th>Precio</th>
                </tr>
            </thead>
            <tbody>
                {% for products in speacial_offers %}
                <tr>
                    <td><img src="#" width="100px" alt="Producto 1"></td>
                    <td>{{products.product_name}}</td>
                    <td>${{products.product_offer_cost}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        
    </div>
    
    <!-- Cards de productos -->
    <div class="container my-4 justify-content-center">
        <h2 class="text-center">Productos Destacados</h2>
        <div class="row">
            {% for products in product_list %}
            <div class="col-12 col-md-4 col-lg-3 mb-4">
                <div class="card">
                    <img src="https://placehold.co/200x200" width="100px" class="card-img-top" alt="Producto">
                    <div class="card-body">
                        <h6 title="{{products.product_name}}" class="card-title text-truncate">{{products.product_name}}</h6>
                        <p class="card-text">
                            {% if products.product_is_offer %}
                            <del style="color: gray;">${{products.product_full_cost}}</del>
                            <b>{{products.product_offer_cost}}</b>
                            {% else %}
                            <b>${{products.product_full_cost}}</b>
                            {% endif %}
                        </p>
                        <button class="btn w-100">
                            Comprar
                         </button>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    {% endblock %}